[package]
name = "gesture-recognition-glove"
version = "0.1.0"
authors = ["Tedi Avrazi"]
edition = "2021"

[[bin]]
name = "gesture-recognition-glove"
test = false
bench = false

[dependencies]
embassy-executor = "0.10.0"
embassy-futures = "0.1"
embassy-net = { version = "0.9.1", features = ["dhcpv4", "medium-ethernet", "tcp", "dns"] }
embassy-sync = "0.8.0"
embassy-time = "0.5.1"
embedded-io-async = "0.7.0"
esp-alloc = { version = "0.11.0", features = ["esp32"] }
esp-backtrace = { version = "0.20.0", features = ["esp32", "panic-handler", "println"] }
esp-bootloader-esp-idf = { version = "0.6.0", features = ["esp32"] }
esp-hal = { version = "1.2", features = ["esp32", "unstable", "log-04"] }
esp-println = { version = "0.18.0", features = ["esp32", "log-04"] }
esp-radio = { version = "1.0.0-beta.1", features = ["esp32", "log-04", "unstable", "wifi"] }
esp-rtos = { version = "0.4.0", features = ["esp32", "esp-radio", "embassy", "log-04"] }
nb = "1.1.0"
static_cell = "2.1.1"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
debug = true

[profile.dev]
opt-level = "z"
